# Generated by Django 5.2.11 on 2026-02-14 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Endorsement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qualifier",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "collaborated_on_research",
                                "Collaborated on research together",
                            ),
                            (
                                "colleague_at_same_institution",
                                "Colleague at same institution",
                            ),
                            (
                                "know_personally_outside_work",
                                "Know personally (outside work)",
                            ),
                            ("met_at_conference_or_event", "Met at conference/event"),
                            ("active_in_same_community", "Active in same community"),
                        ],
                        help_text="Context for how the endorser knows the endorsed user.",
                        max_length=64,
                    ),
                ),
                (
                    "anecdote",
                    models.TextField(
                        blank=True,
                        help_text="A personal anecdote about the relationship.",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "endorsed_user",
                    models.ForeignKey(
                        editable=False,
                        help_text="The user that was endorsed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endorser_user",
                    models.ForeignKey(
                        editable=False,
                        help_text="The user that gave the endorsement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endorsements_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["endorsed_user", "-created_date"],
                        name="endorse_recv_created_ix",
                    ),
                    models.Index(
                        fields=["endorser_user", "-created_date"],
                        name="endorse_give_created_ix",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("endorser_user", "endorsed_user"),
                        name="endorsement_pair_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("endorser_user", models.F("endorsed_user")), _negated=True
                        ),
                        name="endorsement_no_self_ck",
                    ),
                ],
            },
        ),
    ]
